channels:
- conda-forge
dependencies:
- python=3.13.3
- pip<=25.0.1
- pip:
  - mlflow==3.1.1
  - catboost==1.2.8
  - cloudpickle==3.1.1
  - ipywidgets==8.1.7
  - numpy==2.2.5
  - pandas==2.2.3
  - psutil==7.0.0
  - scikit-learn==1.5.2
  - scipy==1.15.3
  - xgboost==3.0.2
name: mlflow-env
